#!MC 1410
$!VarSet |MFBD| = '/'
$!SLICELAYERS SHOW = YES
$!CREATESLICEZONES 
$!PLOTTYPE = CARTESIAN2D
$!TWODAXIS XDETAIL{VARNUM = 2}
$!TWODAXIS YDETAIL{VARNUM = 3}
$!GLOBALTWODVECTOR UVAR = 5
$!GLOBALTWODVECTOR VVAR = 6
$!RESETVECTORLENGTH 
$!ACTIVEFIELDMAPS -= [1]
$!FIELDLAYERS SHOWCONTOUR = YES
$!FIELDLAYERS SHOWSHADE = NO
$!REDRAWALL 
$!RemoveVar |MFBD|
